### ISSUE TITLE
How to add a new type object in frameworks

### ISSUE THREAD

**Issue by lapastina** [hamzahamidi/ajsf#108]
**Describe the bug**
which template:

* [x] MaterialDesignFrameworkModule — Material Design
* [x] Bootstrap3FrameworkModule — Bootstrap 3
* [x] Bootstrap4FrameworkModule — Bootstrap 4
* [x] NoFrameworkModule — plain HTML
* [ ] Other (please specify below)
  
I would like to know the steps to be followed so that I can insert a new type in the existing frameworks.
Example: https://www.npmjs.com/package/ngx-currency-mask

I performed the following, and it did not work:

I created a template "src / lib / material-design-framework / material-currency.component.ts"

I imported and exported the template in the file "src / lib / material-design-framework / index.ts"

I inserted the type into the file "src / lib / material-design-framework / material-design.framework.ts"
'currency': MaterialCurrencyComponent,

I inserted the template into the file "src / lib / widget-library / widget-library.service.ts"
'currency': CurrencyComponent,

I created the file "src / lib / widget-library / currency.component.ts" too.

I inserted the "currency" typo into the "bootstrap-3-framework.component.ts and bootstrap-4-framework.component.ts" files.
this.options.isInputWidget = inArray (this.layoutNode.type, [
        'button', 'checkboxes', 'checkboxes-inline', 'checkboxes', 'color',
        'date', 'datetime-local', 'datetime', 'email', 'file', 'hidden',
        'image', 'integer', 'month', 'number', 'currency', 'password', 'radio'
        'radiobuttons', 'radio-inline', 'radios', 'range', 'reset', 'search',
        'select', 'submit', 'tel', 'text', 'textarea', 'time', 'url', 'week'
      ]);

I also imported the dependency into the package.json file.

But it is not working.

Thankful.

**Comment by pthanos** [comment]
Is there any news regarding this issue? Being able to add custom widgets is very valuable, adding things like pickers or currency inputs is vital
