### ISSUE TITLE
Enum Error: Allowed Values Error in Bootstrap 4 dropdown

### ISSUE THREAD

**Issue by mayankkalbhor** [hamzahamidi/ajsf#117]
**Describe the bug**
which template:

* [ ] MaterialDesignFrameworkModule — Material Design
* [ ] Bootstrap3FrameworkModule — Bootstrap 3
* [x] Bootstrap4FrameworkModule — Bootstrap 4 
* [ ] NoFrameworkModule — plain HTML
* [ ] Other (please specify below)
  
A clear and concise description of what the bug is. I am getting Enum Error: Allowed Values Error in Bootstrap 4 dropdown. The same thing works if i use Material Design. This error is reproducible in the demo also which is given with this library. 

**To Reproduce**

1. Go to https://hamidihamza.com/Angular6-json-schema-form/
2. Change Framework to Bootstrap 4
3. Change the state dropdown on the generated form from "NV" to "None"
4. Observe the enum error occurring and breaking the form

**Expected behavior**
The Enum error should not be shown just as the same behavior if we do by selected the Framework as Material Design

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. iOS]  Windows
- Browser [e.g. chrome, safari] Chrome
- Version [e.g. 22] 23 above

Screenshot attached.
![image](https://user-images.githubusercontent.com/5929696/59600323-7c2ed080-911e-11e9-82b5-c7170d550b1a.png)

**Comment by mayankkalbhor** [comment]
@hamzahamidi Can you please help in the above issue

**Comment by hamzahamidi** [comment]
Can you try using version 7.2.0?
