### ISSUE TITLE
No space between input and label for checkbox

### ISSUE THREAD

**Issue by jma** [hamzahamidi/ajsf#118]
**Describe the bug**
which template:

* [ ] MaterialDesignFrameworkModule — Material Design
* [ ] Bootstrap3FrameworkModule — Bootstrap 3
* [X] Bootstrap4FrameworkModule — Bootstrap 4
* [ ] NoFrameworkModule — plain HTML
* [ ] Other (please specify below)
  
No space between input and label for checkboxes.

**To Reproduce**

1. compare example: https://hamidihamza.com/Angular6-json-schema-form/?set=asf&example=asf-titlemap-examples&framework=bootstrap-4&language=en
to the official Bootstrap documentation: https://getbootstrap.com/docs/4.0/components/forms/

**Expected behavior**
More space between input and  label.

**Comment by rdgoutiyama** [comment]
Same in MaterialDesignFrameworkModule

**Comment by thomasdunn** [comment]
You can add some padding between checkbox and label from the stylesheet of the component hosting `<json-schema-form>`

```css
json-schema-form ::ng-deep input[type=checkbox] + span {
  padding-left: 6px;
}
```
