### ISSUE TITLE
Angular Material Submit button to right?

### ISSUE THREAD

**Issue by rdgoutiyama** [hamzahamidi/ajsf#128]
**Describe the bug**
which template:

* [x ] MaterialDesignFrameworkModule — Material Design
* [ ] Bootstrap3FrameworkModule — Bootstrap 3
* [ ] Bootstrap4FrameworkModule — Bootstrap 4
* [ ] NoFrameworkModule — plain HTML
* [ ] Other (please specify below)
  
Submit button its to left, but i need this to right. 

My form:

> {
    "schema": {
      "type": "object",
      "title": "Comment",
      "properties": {
        "nmTipoFuncionalidade": {
          "title": "Nome",
          "type": "string",
          "appearance": "outline",
          "maxLength": 200,
        },
        "dsTipoFuncionalidade": {
          "title": "Descrição",
          "type": "string",
          "appearance": "outline",
          "maxLength": 200,
        },
      },
      "required": [
        "nmTipoFuncionalidade",
        "dsTipoFuncionalidade",
      ]
    },
    "layout": [
      {
        "key": "nmTipoFuncionalidade",
        "validationMessages": {
          "required": 'test.',
        }
      },
      {
        "key": "dsTipoFuncionalidade",
        "validationMessages": {
          "required": 'test',
        }
      },
      {
        "type": "submit",
        "title": 'Save',
      },
    ],
    "data": {
      "idTipoFuncionalidade": "",
      "nmTipoFuncionalidade": "",
      "dsTipoFuncionalidade": "",
    }
  }

**Comment by a2928897** [comment]
I got same problem, thanks a lot

**Comment by shervinee** [comment]
Have you tried adding flexbox to the submit button within the layout section?

**Comment by khaldrago96** [comment]
> Have you tried adding flexbox to the submit button within the layout section?

Hi could you please tell me if its possible to have custom styling on the form? For instance, if I want to make the size of the input field bigger or change the background color of one element
