### ISSUE TITLE
Support for Additional Properties, AnyOf, OneOf, Nullable

### ISSUE THREAD

**Issue by soumyakantiroychowdhury** [hamzahamidi/ajsf#130]
React JSON Schema supports all features mentioned above. Are these supported? I do not see those examples in the playground. If not, when we can expect those?

Thanks in advance.

**Comment by pandeyop** [comment]
We are working on a project which has a critical requirement for support of oneOf & anyOf in the JSON Schema Form. We find this to be very useful and would be great to have support for these additional features of the schema.

**Comment by baflo** [comment]
Could you please reopen this? This seems to be a big issue :/
