### ISSUE TITLE
Support for File Upload widget <input type="file">

### ISSUE THREAD

**Issue by bhamscott** [hamzahamidi/ajsf#133]
Need ability to add a file upload widget to the form and have the uploaded objects (as Files[] or FileList[]) be added to the data onSubmit() of the rendered form

Add a file input control to the widget library to handle single or multiple upload actions to a form and collect the uploaded file(s) to be sent to the submit() handler for post processing/transfer to server.

**Context**
 File uploads are a fundamental component of form submission tasks

The ability to easily add a file upload widget to a form vs trying to "roll your own" as a custom control is needed.

**Possible Implementation**
Add the element similar to the date field where the type="string" and the format="file"
Use existing material-file.component.ts file as a host widget for the control.

**Comment by Rajat0023** [comment]
Hi, Any update on the file upload feature??

**Comment by maxfriedmann** [comment]
material-file.component.ts still seems to be in progress. We needed that component too, but without adding the files to the formData itself, we rather needed them right before submit as base64. If that matches your needs too, here's the component:

**jsf-file-widget.component.ts**
```typescript
import { Component, Input, OnInit } from "@angular/core";
import { JsonSchemaFormService } from "angular6-json-schema-form";

@Component({
  templateUrl: "./jsf-file-widget.component.html"
})
export class JSFFileWidgetComponent implements OnInit {

  @Input() public layoutNode: any;

  constructor(private jsf: JsonSchemaFormService) { }

  public ngOnInit() {
    this.jsf.initializeControl(this);
  }

  public onFileSelect(event: any) {
    if (!this.jsf.data.files)
      this.jsf.data.files = {};
    if (event.target.files.length > 0) {
      const file: File = event.target.files[0];
      const reader = new FileReader();
      reader.readAsDataURL(file);
      reader.onload = () => {
        this.jsf.data.files[this.layoutNode.name] = reader.result;
      };
      reader.onerror = (error) => {
        throw error;
      };
    }
  }
}
```

**jsf-file-widget.component.html**
```html
<input type="file" (change)="onFileSelect($event)">
```
**Register somewhere via widgetLibraryService**
```typescript
  constructor(widgetLibraryService: WidgetLibraryService) {
    widgetLibraryService.registerWidget("file", JSFFileWidgetComponent);
  }
```

**Grab Files before Submit**
```typescript
export class FormComponent {

  @ViewChild(JsonSchemaFormComponent)
  public jsonSchemaFormComponent: JsonSchemaFormComponent;

  public submit() {
    console.log("files: ", this.jsonSchemaFormComponent.jsf.data.files);
  }

}

```

**Comment by naji-makhoul** [comment]
@maxfriedmann how can clear file selection when form reseted?
