### ISSUE TITLE
Is it possible to use PrimeNG UI Framework or Any other UI Framework which is not listed here

### ISSUE THREAD

**Issue by Rajanusa** [hamzahamidi/ajsf#134]
**Describe the bug**
which template:

* [ ] MaterialDesignFrameworkModule — Material Design
* [ ] Bootstrap3FrameworkModule — Bootstrap 3
* [ ] Bootstrap4FrameworkModule — Bootstrap 4
* [ ] NoFrameworkModule — plain HTML
* [x] Other (please specify below)
  PrimeNG
I would like to whether PrimeNG or any other UI framework which is not listed above can be used?

**To Reproduce**

1. ...

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Log output covering before error and any error statements**

```logs
Insert log hereCopy
```

**Additional context**

**Detailed Description**

**Context**

**Possible Implementation**

I would like to use PrimeNG UI Framework

**Comment by RS-Roshi** [comment]
Yes it is possible and you need to add all components of Primeng to
framework library
