### ISSUE TITLE
When returnEmptyFields is enabled, errors are logged to Browser console

### ISSUE THREAD

**Issue by schuberttobias** [hamzahamidi/ajsf#139]
**Describe the bug**
which template:

* [x] MaterialDesignFrameworkModule — Material Design
* [x] Bootstrap3FrameworkModule — Bootstrap 3
* [x] Bootstrap4FrameworkModule — Bootstrap 4
* [x] NoFrameworkModule — plain HTML
* [x] Other (please specify below)
  
When the option `returnEmptyFields` is set to true, errors are logged to Browser console.

**To Reproduce**

1. Open [example playground](https://hamidihamza.com/Angular6-json-schema-form/).
2. Open Web console in Firefox (or related tools in other Browsers)
3. Enable "Return empty fields"
4. Change Framework so the change of step 2 is applied (see https://github.com/hamzahamidi/Angular6-json-schema-form/issues/138)
5. Errors appear in the Web console:
> set error: Invalid JSON Pointer: main-es2015.f948d22036a6e5d8cf1b.js:1:1248016

**Expected behavior**
No errors appear in the Web console

**Screenshots**
![angular6-json-schema-form bug returnEmptyFields](https://user-images.githubusercontent.com/17709711/63008102-37a38500-be82-11e9-9c81-0abb778890b6.PNG)

**Desktop (please complete the following information):**

- OS: Windows 7
- Browser: Firefox
- Version: 68.0.1

**Log output covering before error and any error statements**

```logs
set error: Invalid JSON Pointer: 2 main-es2015.f948d22036a6e5d8cf1b.js:1:1248016
    Angular 56
        set
        data
        forEachDeep
        data
        validateData
        buildFormGroup
        activateForm
        initializeForm
        updateForm
        ngOnChanges
        hu
        hu
        hu
        $u
        ou
        updateDirectives
        cu
        vu
        yu
        cu
        vu
        yu
        cu
        vu
        bu
        cu
        vu
        yu
        cu
        vu
        bu
        cu
        detectChanges
        tick
        next
        invoke
        onInvoke
        invoke
        run
        run
        next
        i
        __tryOrUnsub
        next
        _next
        next
        next
        emit
        ta
        ia
        onInvokeTask
        invokeTask
        runTask
        invokeTask
        y
        k
```

**Detailed Description**
Fix code, so no errors are logged.

**Comment by hans-pragt** [comment]
I see the same problem in @ajsf/material v0.1.4.

**Comment by jonathanantoine** [comment]
I have the same issue
