### ISSUE TITLE
Multiple Select UI with material doesn't show like <mat-select>

### ISSUE THREAD

**Issue by sujoydc** [hamzahamidi/ajsf#147]
**Describe the bug**
which template:
* [ ] MaterialDesignFrameworkModule — Material Design
The UI using material design is not looking good. Without multi select option it shows like material single select nicely. 

**To Reproduce**

1.  
{
    "schema": {
      "type": "array",
      "items": {
        "type": "string",
        "enum": [
          "a",
          "b",
          "c"
        ]
      },
      "uniqueItems": true
    }
}

**Expected behavior**
The UI should be like this 
https://material.angular.io/components/select/overview#multiple-selection

**Screenshots**
<img width="1012" alt="image" src="https://user-images.githubusercontent.com/1069026/64836421-d32a3180-d5b7-11e9-9ebf-69a046118400.png">

**Desktop (please complete the following information):**

- OS: Windows 10, Mac
- Browser: Chrome, Firefox
- Version:

**Comment by shervinee** [comment]
This seems to be due to the fact that the library uses a default form definition when rendering the schema which is the same as [the library here](https://github.com/json-schema-form/angular-schema-form/blob/master/docs/index.md#default-form-types). For having a drop-down similar to mat-select you need to remove the "type" and "items" keys from your schema and have something like: 
`{
"schema": {
"type": "string",
"name": "Multi-Select"
"enum": [
"a",
"b",
"c"
]
"uniqueItems": true
}
}`

**Comment by sujoydc** [comment]
@shervinee Thanks for your reply. 
But this solution only gives a single select. 
It doesn't work with multiple-select like below. 
https://material.angular.io/components/select/overview#multiple-selection

**Comment by sujoydc** [comment]
I have copied your Material Select component and replaced that with 'checkboxes'. This is working with few issues like the selected data is not getting shown back to the UI. Working on that now.

**Comment by sujoydc** [comment]
I have asked a question in SO regarding the form edit callback issue:
https://stackoverflow.com/questions/58036755/angular6-json-schema-form-issue-with-multi-select-form-change-event

**Comment by sujoydc** [comment]
@hamzahamidi I know you are busy but could you please look into this for a minute? I am using 7.2.0 with Angular v7. 
https://stackoverflow.com/questions/58036755/angular6-json-schema-form-issue-with-multi-select-form-change-event

**Comment by sujoydc** [comment]
@hamzahamidi Could you please look into this?

**Comment by hamzahamidi** [comment]
The type array is translated to checkboxes ( multiple selections ). If you want Select UI you can try the following schema:
```javascript
{
   "schema":{
      "type":"object",
      "properties":{
         "only-one-choice":{
            "type":"string",
            "enum":[
               "a",
               "b",
               "c"
            ]
         }
      },
      "uniqueItems":true
   }
}
```

**Comment by sujoydc** [comment]
@hamzahamidi First of all thanks a lot for your reply. 
It would be great if you could read my StackOverflow question (https://stackoverflow.com/questions/58036755/angular6-json-schema-form-issue-with-multi-select-form-change-event). 
The ask is to have a multiple selection (not with multiple checkboxes) like Material Multi-Select. So I have overridden your checkboxes with MaterialSelectComponent. Everything works nicely with the UI but the value change is not getting emitted so I don't get the values of that Multi-Select component. 

I have debugged your code in Chrome and figured that FormArray which is in case of this multi-select, is not emitting valueChanges event (For FormControl type it works so the same MaterialSelectComponent with 'multiple' as false works but 'multiple' as true won't).

Is there is bug, limitation for FormArray?
