### ISSUE TITLE
Problems with nested requirements

### ISSUE THREAD

**Issue by trsh** [hamzahamidi/ajsf#15]
## Issue type
I'm submitting a (check one):
[ x] Bug report
[x ] Feature request
[ ] Regression (something that used to work, but stopped working in a newer version)
[ ] Support request
[ ] Documentation issue or request

## Prerequisites
Before posting, make sure you do the following (check all):
[x ] Confirm you are using the latest versions of all necessary packages (or if not, explain why not)

## Current behavior
When you have parent property, that isn't required, but has self required properties, it gives an error. I don't know how to solve this. https://json-editor.github.io/json-editor/ fro example, has optional objects as initially non listed and addable. So when you add the object, it's properties are required, but can also skip the whole object, as it is optional.

**Comment by hamzahamidi** [comment]
Sorry for the late answer, can you make a repository or give the JSON schema to reproduce this issue?

**Comment by trsh** [comment]
https://gist.githubusercontent.com/trsh/b710a2ed982c4064c06c4d0fae7cd5e4/raw/a5fedce98aa2647e2e40b621eb5ddaada2631352/json

The default behavior should be that I do not get any errors about 'y', as I can skip whole 'x' object (unless I chose to USE it), as IT is not required.

Ideally not required objects/whatever should be Hidden by default, and addable visa some checkbox.

If you check https://json-editor.github.io/json-editor/ -> Location -> Properties, u will see the idea.

**Comment by trsh** [comment]
@hamzahamidi ?

**Comment by trsh** [comment]
@hamzahamidi I think ppl just haven't tough about this scenario?

**Comment by bradley-redford** [comment]
Any update on this issue ?
