### ISSUE TITLE
Creating new framework

### ISSUE THREAD

**Issue by Thorski** [hamzahamidi/ajsf#151]
**Describe the bug**

I am trying to implement my own framework.  
I think there should be a framework guide.   

My current confusion is what is all of the 
'boundControl' logic in some of the components in existing frameworks, what is it for and 
when exactly is it necessary.   

Some of the widget templates have duplicated sections with  *ngIf=boundControl and *ngIf=!boundControl, with the only difference being [formControl]="formControl" specified.

Some widgets do not have such sections.
Why is this needed and when?

In my old version of the original library these duplicated sections do not exist and there is no check for boundControl.

Thanks for any guidance.

**Comment by RS-Roshi** [comment]
I made my famework using PrimeNG and bount countrol isn't necessary in
anyway

**Comment by Thorski** [comment]
@RS-Roshi wow that is exactly what I am doing.   I don't suppose your framework is or could be made publicly available?   Or made available to me at least?  :)   Might save me a bit of work!

**Comment by RS-Roshi** [comment]
Sure can you i wait a day i will send you and soon will be public

**Comment by Thorski** [comment]
That would be fantastic!
Thank you so much!

**Comment by zee85** [comment]
What type of framework are you guys talking about? I myself always thought describing forms in JSON naturally leads to the idea of building an interface which would allow none technical users to build "types" of that could than be transcribed to forms and persisted.
