### ISSUE TITLE
Nested Arrays getControl error: Unable to find "0" item in FormGroup.

### ISSUE THREAD

**Issue by neil-coutinho** [hamzahamidi/ajsf#152]
**Describe the bug**
which template:

* [ ] MaterialDesignFrameworkModule — Material Design
* [ ] Bootstrap3FrameworkModule — Bootstrap 3
* [#] Bootstrap4FrameworkModule — Bootstrap 4
* [ ] NoFrameworkModule — plain HTML
* [ ] Other (please specify below)
  
Deeply nested arrays throw the following error 
_getControl error: Unable to find "0" item in FormGroup._

**To Reproduce**

[https://stackblitz.com/edit/angular6-json-schema-form-jw5qql](https://stackblitz.com/edit/angular6-json-schema-form-jw5qql)

- OS: iOS
- Browser Chrome
- Version 77.0.3865.90

**Additional context**

1. I have a script that manually generates they layout from a schema

1. The layout throws errors for nested array element i.e. modules.FoodAndBeverageIngredientInformationModuleType.foodAndBeverageIngredient[].subIngredient[].ingredientName[].value

The key to the nested array seems right. Am I missing something or is the layout incorrect?

Would appreciate any help @hamzahamidi 

Thanks

**Comment by neil-coutinho** [comment]
@hamzahamidi thoughts?

**Comment by neil-coutinho** [comment]
An updated example using the [Deep Recursive References](https://hamidihamza.com/ajsf/?set=ng-jsf&example=ng-jsf-deep-ref&framework=bootstrap-4&language=en) schema from the examples 

[https://stackblitz.com/edit/angular-c1mzvk](https://stackblitz.com/edit/angular-c1mzvk
)
With layout  = ['*'] it works perfectly, I guess my layout is incorrect.

**Comment by neil-coutinho** [comment]
@hamzahamidi any update on this?

**Comment by hamzahamidi** [comment]
@neil-coutinho I'm sorry I was busy. Did you find a solution to your issue?

**Comment by neil-coutinho** [comment]
@hamzahamidi  Unfortunately no. Though I did narrow the issue down to schema properties of type array which have items with a $ref URL to another schema property which in turn also has a $ref to another different property as shown in the example of Deep Recursive References above.


Also, I discovered a second issue related to this, will raise another ticket. Nested arrays i.e. Arrays inside arrays only show the first item when data is provided

Hope you can take a look at them 

Thank you. Great lib.

**Comment by sksahil152** [comment]
@neil-coutinho  and @hamzahamidi please tell something about this issue,
