### ISSUE TITLE
how to define autocomplete, with server side search

### ISSUE THREAD

**Issue by GlauberF** [hamzahamidi/ajsf#157]
**Describe the bug**
I need to define some fields that are of autocomplete type of material and that at the moment the user type, search the server.
Is there any example of how I can do it, because I looked in various places / documentation and found nothing

* [x] MaterialDesignFrameworkModule — Material Design
* [ ] Bootstrap4FrameworkModule — Bootstrap 4
* [ ] Bootstrap3FrameworkModule — Bootstrap 3
* [ ] NoFrameworkModule — plain HTML
* [ ] Other (please specify below)

**Comment by shervinee** [comment]
Have there been any updates on this? we're actively looking for a way to do that for our project
