### ISSUE TITLE
Strange 'number' field behavior

### ISSUE THREAD

**Issue by sverdlov** [hamzahamidi/ajsf#161]
**Describe the bug**
which template:

* [x] MaterialDesignFrameworkModule — Material Design
* [ ] Bootstrap3FrameworkModule — Bootstrap 3
* [ ] Bootstrap4FrameworkModule — Bootstrap 4
* [ ] NoFrameworkModule — plain HTML
* [ ] Other (please specify below)
  
Can't input float numbers.

**To Reproduce**
[Stackblitz](https://angular-eb6csp.stackblitz.io) here is example project. Try to type float value (ex.: 15.1)

**Expected behavior**
Float numbers must be entered.

**Additional context**
I notice it happen when data is set. In your example [here](https://hamidihamza.com/Angular6-json-schema-form/) everything works as expected

**Comment by NileshPanchal** [comment]
Hi, 
I am also facing the same issue.

Below is the version / browser details :- 

angular6-json-schema-form - v7.3.0

and

<img width="661" alt="Screenshot 2019-11-07 at 12 03 01 PM" src="https://user-images.githubusercontent.com/1697698/68365511-d294be00-0156-11ea-8813-712a0ca9a4cb.png">

Browser :- Google Chrome - Version 76.0.3809.132 (Official Build) (64-bit)

**Comment by NileshPanchal** [comment]
@hamzahamidi 
Did you get time to check on this?
