### ISSUE TITLE
Multiple events are fired even when clicking objects outside the form. Is it because I have two way data binding and form defined?

### ISSUE THREAD

**Issue by Mmatiasn** [hamzahamidi/ajsf#165]
Multiple events are fired even when clicking objects outside the form.
which template:

* [X] MaterialDesignFrameworkModule — Material Design
* [ ] Bootstrap3FrameworkModule — Bootstrap 3
* [ ] Bootstrap4FrameworkModule — Bootstrap 4
* [X] NoFrameworkModule — plain HTML
* [ ] Other (please specify below)
  

**To Reproduce**

1.
Defined your component like so:
```
                <json-schema-form
                    *ngIf="jsonSchemaForm.custom.display"
                    [debug]="jsonSchemaForm.debug"
                    [schema]="jsonSchemaForm.schema"
                    [framework]="jsonSchemaForm.framework"
                    [layout]="jsonSchemaForm.layout"
                    [(data)]="jsonSchemaForm.data"
                    (onChanges)="jsonSchemaForm.events.onChanges($event)"
                    (onSubmit)="jsonSchemaForm.events.onSubmit($event)"
                    (isValid)="jsonSchemaForm.events.isValid($event)"
                    (validationErrors)="jsonSchemaForm.events.validationErrors($event)"
                    (formSchema)="jsonSchemaForm.events.formSchema($event)"
                    (formLayout)="jsonSchemaForm.events.formLayout($event)"
                >
                </json-schema-form>
```

**Expected behavior**
Events should only trigger when values change. When they do change, they should only trigger once or as many times as they were registered by user.

**Screenshots**
![image](https://user-images.githubusercontent.com/12785825/69384168-92225d80-0c89-11ea-8175-628b43b53538.png)

**Desktop (please complete the following information):**

- OS: [Windows 10]
- Browser [Chrome]
- Version [Version 78.0.3904.108 (Official Build) (64-bit)]

**Additional context**
Angular 8

**Context**

Two way binding is critical for Angular apps.

Two way binding is critical for Angular apps.

**Possible Implementation**
I was unable to figure out what was causing the issue.

**Comment by levyitay** [comment]
Same here
