### ISSUE TITLE
IVY

### ISSUE THREAD

**Issue by Gobikannan** [hamzahamidi/ajsf#166]
Getting error with the production build when Ivy is enabled in tsconfig.json.

WARNING in Entry point 'angular6-json-schema-form' contains deep imports into 'C:/WebApp/ClientApp/node_modules/lodash-es/cloneDeep', 'C:/WebApp/ClientApp/node_modules/lodash-es/filter', 'C:/WebApp/ClientApp/node_modules/lodash-es/map', 'C:/WebApp/ClientApp/node_modules/lodash-es/isEqual', 'C:/WebApp/ClientApp/node_modules/lodash-es/uniqueId'. This is probably not a problem, but may cause the compilation of entry points to be out of order.

ERROR in Node does not exist: C:/WebApp/ClientApp/node_modules/angular6-json-schema-form

I really appreciate if someone can help me on this.

Versions:

"@angular/animations": "^8.2.14",
    "@angular/cdk": "^8.2.3",
    "@angular/common": "^8.2.14",
    "@angular/compiler": "^8.2.14",
    "@angular/core": "^8.2.14",
    "@angular/forms": "^8.2.14",
    "@angular/platform-browser": "^8.2.14",
    "@angular/platform-browser-dynamic": "^8.2.14",
    "@angular/router": "^8.2.14",
"angular-tree-component": "^8.5.1",
    "angular6-json-schema-form": "8.0.0",
"classlist.js": "^1.1.20150312",
    "core-js": "3.4.4",
    "cytoscape": "^3.11.0",
    "date-fns": "^2.8.1",
    "eva-icons": "^1.1.2",
    "moment": "^2.24.0",
    "powerbi-client": "^2.10.2",
    "rxjs": "6.5.3",
    "tslib": "^1.10.0",
    "typeface-exo": "0.0.22",
    "web-animations-js": "2.3.2",
    "zone.js": "^0.10.2"

"devDependencies": {
    "@angular-devkit/build-angular": "0.803.19 ",
    "@angular/cli": "^8.3.19",
    "@angular/compiler-cli": "^8.2.14",
    "@angular/flex-layout": "~8.0.0-beta.27",
    "@angular/language-service": "^8.2.14",
    "@angular/material": "^8.2.3",
    "@schematics/angular": "^8.3.19",
    "@types/cytoscape": "^3.8.3",
    "@types/jasmine": "3.4.0",
    "@types/jasminewd2": "2.0.6",
    "@types/node": "10.7.1",
    "bootstrap": "^4.3.1",
    "codelyzer": "^5.0.1",
    "jasmine-core": "3.4.0",
    "jasmine-spec-reporter": "4.2.1",
    "karma": "4.3.0",
    "karma-chrome-launcher": "3.1.0",
    "karma-cli": "2.0.0",
    "karma-coverage-istanbul-reporter": "2.1.0",
    "karma-jasmine": "2.0.1",
    "karma-jasmine-html-reporter": "1.4.2",
    "karma-junit-reporter": "^1.2.0",
    "karma-spec-reporter": "0.0.32",
    "lodash": "^4.17.15",
    "lodash-es": "^4.17.15",
    "protractor": "6.0.0",
    "ts-node": "3.2.2",
    "tslint": "^5.7.0",
    "typescript": "~3.4.5"
  }

**Comment by maxfriedmann** [comment]
@Gobikannan If you update to the latest Angular 9 RC version, your error disappears. 

Nevertheless, another Error occurs: a @ViewChild() doesn't have the new not optional second parameter, the Ivy Compiler doesn't show which one. If I remove this package, it disappears as well.

As soon as Angular 9 is out, we will migrate to the latest version. I need to know if someone is working on the issues this package has with either Ivy or Angular 9 or if we should rather look for alternatives?

**Comment by maxfriedmann** [comment]
https://www.npmjs.com/package/angular7-json-schema-form seems to work !

**Comment by hamzahamidi** [comment]
Can you share a demo reproducing this problem?

**Comment by Gobikannan** [comment]
Thanks for the reply. I can not use RC version for now, will try later. 
Cheers,
