### ISSUE TITLE
lodash less than 14.17.12

### ISSUE THREAD

**Issue by ronsensei** [hamzahamidi/ajsf#167]
Versions of lodash lower than 4.17.12 are vulnerable to Prototype Pollution. The function defaultsDeep could be tricked into adding or modifying properties of Object.prototype using a constructor payload.

Solution: update all lodash dependencies to version 4.17.12 or higher.

**Comment by hamzahamidi** [comment]
Fixed in https://github.com/hamzahamidi/ajsf/commit/56c4c69c5c590e3e1e8ce6e3718e9cc6214180b4
