### ISSUE TITLE
Can't use without material library

### ISSUE THREAD

**Issue by Kalcode** [hamzahamidi/ajsf#17]
**Describe the bug**
which template:

* [ ] MaterialDesignFrameworkModule — Material Design
* [ ] Bootstrap3FrameworkModule — Bootstrap 3
* [ ] Bootstrap4FrameworkModule — Bootstrap 4
* [X] NoFrameworkModule — plain HTML
* [ ] Other (please specify below)
  
Can't use NoFrameworkModule without requiring flex-layout or angular/material

**To Reproduce**

1. Import NoFrameworkModule without angular/material

**Expected behavior**
To work without these dependencies. 

Might be doing something wrong, but using the NoFrameworkModule I can't seem to get it to start without it throwing errors for flex-layout, material and cdk

**Comment by hamzahamidi** [comment]
Are you sure you imported Bootstrap4FrameworkModule like this, note that you shouldn't import `JsonSchemaFormModule` :
```typescript
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';

import { NoFrameworkModule } from 'angular6-json-schema-form';

import { AppComponent } from './app.component';

@NgModule({
  declarations: [ AppComponent ],
  imports: [
    BrowserModule
    Bootstrap4FrameworkModule
  ],
  providers: [],
  bootstrap: [ AppComponent ]
})
export class AppModule { }
```
And you use the component like the following:
```html
<json-schema-form
  loadExternalAssets="true"
  [schema]="yourJsonSchema"
  framework="no-framework"
  (onSubmit)="yourOnSubmitFn($event)">
</json-schema-form>
```
If you still face the same issue, can you make a repository to reproduce this issue?

**Comment by Kalcode** [comment]
<img width="988" alt="screen shot 2018-08-30 at 2 52 33 pm" src="https://user-images.githubusercontent.com/13425721/44875632-653cf180-ac64-11e8-92c0-125b8a9404b0.png">


```ts
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { HttpClientModule } from '@angular/common/http';
import { ApolloModule } from 'apollo-angular';
import { HttpLinkModule } from 'apollo-angular-link-http';
import { NoFrameworkModule } from 'angular6-json-schema-form';

import { AppComponent } from './app.component';
import { LayoutModule } from './modules/layout/layout.module';
import { ApolloProvider } from './graphql/createApollo';

@NgModule({
  bootstrap: [AppComponent],
  declarations: [
    AppComponent,
  ],
  imports: [
    BrowserModule,
    HttpClientModule,
    ApolloModule,
    HttpLinkModule,
    LayoutModule,
    NoFrameworkModule,
  ],
  providers: [
    ApolloProvider,
  ],
})
export class AppModule { }
```

Sure give me a few minute to get one going.

**Comment by Kalcode** [comment]
@hamzahamidi 
https://github.com/Kalcode/angular6-json-schema-form-test-app

Same error brand new repo. Not sure where its happening, hoping I could find it but I haven't. Hopefully you are able to help. Thanks.

**Comment by hamzahamidi** [comment]
Yes , I noticed that you need to install @angular/material whether or not you use material component.

**Comment by jhiemer** [comment]
@hamzahamidi any plans to solve this? I think it is bad practise to include more libraries than really needed.

**Comment by Selion05** [comment]
@hamzahamidi  you also have to import the Material frame work module. eg try https://github.com/Selion05/angular-json-schema-test without importing 
```logs

Uncaught Error: Template parse errors:
'json-schema-form' is not a known element:
```

**Comment by hubertkubiak** [comment]
Same for me. I can use "framework="no-framework" but only if I import the "MaterialDesignFrameworkModule" or "Bootstrap4FrameworkModule".  The "NoFrameworkModule" doesn't provide the "json-schema-form" element.

**Comment by woutervs** [comment]
Any news on this?
When I try to use it with bootstrap-4 i'm forced to install:
import { FlexLayoutModule } from '@angular/flex-layout';
import { Bootstrap4FrameworkModule } from 'angular6-json-schema-form';
import { MaterialDesignFrameworkModule } from 'angular6-json-schema-form';
As well as lodash-es
4 libraries that I don't need.
