### ISSUE TITLE
README error 

### ISSUE THREAD

**Issue by BobCashStory** [hamzahamidi/ajsf#176]
**Describe the bug**
which template:
all template have error in the README it's say asjf instead of ajsf
* [ x] MaterialDesignFrameworkModule — Material Design
* [ x] Bootstrap3FrameworkModule — Bootstrap 3
* [ x] Bootstrap4FrameworkModule — Bootstrap 4
* [ x] NoFrameworkModule — plain HTML
* [ ] Other (please specify below)
  

**To Reproduce**

1. ...

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Log output covering before error and any error statements**

```logs
Insert log hereCopy
```

**Additional context**

**Detailed Description**

**Context**

**Possible Implementation**

**Comment by BobCashStory** [comment]
https://github.com/hamzahamidi/ajsf/pull/177

**Comment by hamzahamidi** [comment]
Thank you for fixing the error
