### ISSUE TITLE
Equality condition doesn't work properly like in demo

### ISSUE THREAD

**Issue by nikluwfy** [hamzahamidi/ajsf#183]
**Describe the bug**
which template:

* [x] MaterialDesignFrameworkModule — Material Design
* [ ] Bootstrap3FrameworkModule — Bootstrap 3
* [ ] Bootstrap4FrameworkModule — Bootstrap 4
* [x] NoFrameworkModule — plain HTML
* [ ] Other (please specify below)
  

**To Reproduce**

1. I played around with schema in demo playground (hamidihamza.com/ajsf) and reproduced the exact schema with exact behavior I wanted, everything works fine
2. I created new component for angular through `ng generate` and did add nothing except component's class property `jsonSchema` which obviously contains schema itself and layout inside (I'm using layout instead of form).
3. I added `<json-schema-form>` to my HTML and passed all expected values inside

**Expected behavior**
I expected additional selector and input to be created if condition's statement is true (I will provide schema down below), but one thing I figured out is that condition property does work, but when it comes to equality statements it stops working. Wonderful thing is that it totally works in demo but not inside of my code, though I copy-pasted schema.

**Screenshots**

Behavior in demo:
![image](https://user-images.githubusercontent.com/59794444/73193895-fa7f3680-4133-11ea-975c-2629d2366ec4.png)

![image](https://user-images.githubusercontent.com/59794444/73193949-0ec33380-4134-11ea-9d89-cd43567f4c4b.png)

Behavior of copy-pasted schema and layout from demo in my code:
![image](https://user-images.githubusercontent.com/59794444/73194057-3ca87800-4134-11ea-8782-87ccae40c1bc.png)

Behavior of schema and layout from demo in my code without equality condition:
`condition: "switchArr[arrayIndex].ruleSelector"`
![image](https://user-images.githubusercontent.com/59794444/73194253-9315b680-4134-11ea-9bcd-4ff86dfba030.png)

HTML: 
```html
<h1 [ngStyle]="{padding: '10px 0 0 50px'}">it worksssss</h1>
<json-schema-form
  loadExternalAssets="true"
  framework="no-framework"
  (onSubmit)="onSubmit($event)"
  [layout]="jsonSchema.layout"
  [schema]="jsonSchema.schema">
</json-schema-form>
```
Schema and layout:
```json
  jsonSchema = {
    schema: {
      type: "object",
      properties: {
        switchArr: {
          type: "array",
          items: {
            type: "object",
            properties: {
              payload_one: {
                placeholder: "Payload",
                type: "string"
              },
              payload_two: {
                placeholder: "Payload",
                type: "string"
              },
              ruleSelector: {
                title: "Expression",
                type: "string",
                enum: [">", "<", ">=", "<=", "==", "between"],
                "description": "Will be used for evil."
              },
              formatSelector: {
                title: "Format",
                type: "string",
                enum: ["msg", "flow", "global", "string", "number", "jsonata"]
              },
              conditionalSelector: {
                title: "Format",
                type: "string",
                enum: ["msg", "flow", "global", "string", "number", "jsonata"]
              }
            }
          }
        }
      }
    },
    layout: [
      {
        key: "switchArr",
        type: "array",
        itemsCount: 1,
        items: [
          {
            type: "section",
            items: [
              {
                type: "section",
                display: "flex",
                "flex-direction": "row",
                items: [
                  "switchArr[].ruleSelector",
                  "switchArr[].formatSelector",
                  "switchArr[].payload_one"
                ]
              },
              {
                type: "flex",
                "flex-flow": "row",
                condition: "switchArr[arrayIndex].ruleSelector=='between'",
                items: [
                  "switchArr[].conditionalSelector",
                  "switchArr[].payload_two"
                ]
              }
            ]
          }
        ]
      }
    ]
  };
```

- OS: Windows 10
- Browser Chrome
- Versions: chrome - latest, windows 64 bit pro, package - angular7-json-schema-form

Hope for soon response, thanks beforehand.

**Comment by hamzahamidi** [comment]
Can you share your `package.json` ? The demo is using @ajsf 0.1.3

**Comment by nikluwfy** [comment]
Sure.
![image](https://user-images.githubusercontent.com/59794444/73195316-55199200-4136-11ea-9c02-98a44980842a.png)
![image](https://user-images.githubusercontent.com/59794444/73195350-6367ae00-4136-11ea-8a3f-5c2f6bad5564.png)

`{
  "name": "dev-schema",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@ajsf/material": "^0.1.3",
    "@angular/animations": "~8.2.14",
    "@angular/cdk": "~8.2.3",
    "@angular/common": "~8.2.14",
    "@angular/compiler": "~8.2.14",
    "@angular/core": "~8.2.14",
    "@angular/flex-layout": "7.0.0-beta.19",
    "@angular/forms": "~8.2.14",
    "@angular/material": "^8.2.3",
    "@angular/platform-browser": "~8.2.14",
    "@angular/platform-browser-dynamic": "~8.2.14",
    "@angular/router": "~8.2.14",
    "@types/body-parser": "^1.17.1",
    "@types/express": "^4.17.2",
    "angular7-json-schema-form": "^1.0.4",
    "body-parser": "^1.19.0",
    "cors": "^2.8.5",
    "express": "^4.17.1",
    "http": "0.0.0",
    "path": "^0.12.7",
    "pg": "^7.17.1",
    "pg-hstore": "^2.3.3",
    "rxjs": "~6.4.0",
    "sequelize": "^5.21.3",
    "tslib": "^1.10.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.803.23",
    "@angular/cli": "~8.3.23",
    "@angular/compiler-cli": "~8.2.14",
    "@angular/language-service": "~8.2.14",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^8.9.5",
    "codelyzer": "^5.0.0",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.5.3"
  }
}`

**Comment by hamzahamidi** [comment]
``angular7-json-schema-form`` is a fork of this library. uninstall it:  npm uninstall 

And just to be safe check your module where you import ajsf

$ npm install @ajsf/material

```typescript
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';

import { MaterialDesignFrameworkModule } from '@ajsf/material';

import { AppComponent } from './app.component';

@NgModule({
  declarations: [ AppComponent ],
  imports: [
    MaterialDesignFrameworkModule
  ],
  providers: [],
  bootstrap: [ AppComponent ]
})
export class AppModule { }
```

**Comment by nikluwfy** [comment]
Using this package everything works fine, thank you. Strange though it didn't while `angular7-json-schema-form` was listed in package dependencies, I already tried using `@ajsf/material` separately but didn't work for me first time somehow. Thanks again.
