### ISSUE TITLE
In angular9 lists are displayed only in columns

### ISSUE THREAD

**Issue by james-powis** [hamzahamidi/ajsf#187]
**Describe the bug**
which template:

* [ x] MaterialDesignFrameworkModule — Material Design
* [ ] Bootstrap3FrameworkModule — Bootstrap 3
* [ ] Bootstrap4FrameworkModule — Bootstrap 4
* [ ] NoFrameworkModule — plain HTML
* [ ] Other (please specify below)
  
Previously in angular9 on angular6-json-schema-form lists were displayed vertically stacked in rows, after upgrading to Angular8 and then to Angular9 (in rapid fashion), the same layout results in the material cards being organized into wrapping columns. 

This issue was observed on two different projects, one of which is provided in #48.

**To Reproduce**
See https://github.com/james-powis/angular6-json-schema-form-issue

1. ...

**Expected behavior**
Should be displayed as Rows not Columns

**Screenshots**
![Screen Shot 2020-02-11 at 9 27 31 AM](https://user-images.githubusercontent.com/2318207/74256571-cb7ad000-4cb0-11ea-84b2-30fdaecf4113.png)

**Desktop (please complete the following information):**

- OS: OSX 10.15.2
- Browser Chrome
- Version 79.0.39.45.130

**Log output covering before error and any error statements**

```logs
WARNING in Entry point '@ajsf/material' contains deep imports into '/Users/me/git/james-powis/angular6-json-schema-form-issue/node_modules/lodash/cloneDeep'. This is probably not a problem, but may cause the compilation of entry points to be out of order.

WARNING in Entry point '@ajsf/core' contains deep imports into '/Users/me/git/james-powis/angular6-json-schema-form-issue/node_modules/lodash/cloneDeep', '/Users/me/git/james-powis/angular6-json-schema-form-issue/node_modules/lodash/isEqual', '/Users/me/git/james-powis/angular6-json-schema-form-issue/node_modules/ajv/lib/refs/json-schema-draft-06.json', '/Users/me/git/james-powis/angular6-json-schema-form-issue/node_modules/lodash/filter', '/Users/me/git/james-powis/angular6-json-schema-form-issue/node_modules/lodash/map', '/Users/me/git/james-powis/angular6-json-schema-form-issue/node_modules/lodash/uniqueId'. This is probably not a problem, but may cause the compilation of entry points to be out of order.

```

**Comment by hamzahamidi** [comment]
#188

**Comment by hamzahamidi** [comment]
I can reproduce the issue in Angular 9 But I didn't find yet the cause

**Comment by Kaskyi** [comment]
json-schema-form flex-layout-root-widget.form-flex-column div {
    flex: 1 1 100% !important;
  }

**Comment by stiray** [comment]
I am observing same behavior with object types on Angular 11. This is a simple schema that can be used on https://hamidihamza.com/ajsf/ , the object is rendered into two input fields but they are placed in two columns instead (or at least what I would expect) in two rows.

`{
   "schema":{
      "type":"object",
      "properties":{
         "Test object":{
            "type":"object",
            "properties":{
               "test1":{
                  "type":"string",
                  "title":"title 1"
               },
               "test2":{
                  "type":"string",
                  "title":"title 2"
               }
            }
         }
     }
   }
}`
