### ISSUE TITLE
Can't specify layout when schema depth is more than one

### ISSUE THREAD

**Issue by ericct** [hamzahamidi/ajsf#20]
**Describe the bug**
which template:

(does not seem to depend on the template)

* [* ] MaterialDesignFrameworkModule — Material Design
* [ *] Bootstrap3FrameworkModule — Bootstrap 3
* [ ] Bootstrap4FrameworkModule — Bootstrap 4
* [* ] NoFrameworkModule — plain HTML
* [ ] Other (please specify below)
  

**To Reproduce**

1. Render the form with the following spec:
```{
  "schema": {
    "type": "object",
    "properties": {
      "name": {
        "type": "object",
        "properties": {
          "sub-name": {
            "type": "string"
          }
        }
      },
      "other": {
        "type": "string"
      }
    }
  },
  "layout": [
    "*"
  ]
}
```
It works as intended

2. Try to adding constraints on layout, e.g.
```{
  "schema": {
    "type": "object",
    "properties": {
      "name": {
        "type": "object",
        "properties": {
          "sub-name": {
            "type": "string"
          }
        }
      },
      "other": {
        "type": "string"
      }
    }
  },
  "layout": [
    "name",
    "other"
  ]
}
```
Only the fieldset for "name" is generated.

**Expected behavior**
Form rendering should happen even when specifying a field with a depth greater than 1 in the layout.

**Screenshots**
Expected:
![image](https://user-images.githubusercontent.com/22603003/45541609-e0c7a280-b80f-11e8-98a2-435f1bc25bfc.png)

Got:
![image](https://user-images.githubusercontent.com/22603003/45541588-cbeb0f00-b80f-11e8-814d-7e9a3feb8678.png)

**Desktop (please complete the following information):**

- OS: [Linux]
- Browser [any]

**Comment by james-powis** [comment]
This bit me too, the only solution is to explicitly define all the dimensions of the object until this issue is resolved.
