### ISSUE TITLE
Your Conditional example

### ISSUE THREAD

**Issue by Sophos06** [hamzahamidi/ajsf#217]
**Describe the bug**
* [ X ] MaterialDesignFrameworkModule — Material Design

Using your example [here](https://hamidihamza.com/ajsf/?set=asf&example=asf-hack-conditional-required&framework=material-design&language=en):
When the field disappears, it is still in the final generated JSON onSubmit().

**To Reproduce**

1. Check the "switch" checkbox --> e-mail field shows up
2. Fill in your e-mail
3. Uncheck the "Switch" checkbox --> e-mail field disappears

This is fine.
However, even after having disappeared, the e-mail field is still grabbed onSubmit()

**Expected behavior**
The not-displayed field should not be part of the final script

**Screenshots**
OK:
![image](https://user-images.githubusercontent.com/47745063/85006696-bdefbe00-b15a-11ea-9a88-c4be424b1c16.png)

Not OK:
![image](https://user-images.githubusercontent.com/47745063/85006742-cea03400-b15a-11ea-9221-4b15cfafdd84.png)

**Desktop (please complete the following information):**
- OS: Windows 10 Enterprise - build 17134.1488
- Browser Chrome - build 83.0.4103.97 64 bits

**Context**
My final goal is to show up  / remove subforms with condition on enum string instead of a boolean.
If you can show up how to do that... :).
Many thanks and big bravo to your useful demo paltform.

**Comment by sh1nryu** [comment]
Hey, I'm having the same issue. Can we please re-open this to find a solution? If the condition is false, the inputs rendered by that condition should not be included in validation, but they currently are. Any workarounds appreciated...
