### ISSUE TITLE
floatPlaceholder is now floatLabel

### ISSUE THREAD

**Issue by blained3** [hamzahamidi/ajsf#22]
**Describe the bug**
which template:

* [X] MaterialDesignFrameworkModule — Material Design
* [ ] Bootstrap3FrameworkModule — Bootstrap 3
* [ ] Bootstrap4FrameworkModule — Bootstrap 4
* [ ] NoFrameworkModule — plain HTML
* [ ] Other (please specify below)

The updated Material Design no longer uses floatPlaceholder. They changed it to floatLabel.
  
**Expected behavior**
Labels actually float.

I was going to submit a pull request but the change is already in the code, it just hasn't been released.

**Comment by sallaccio** [comment]
Hi,

I noticed that placeholders do not float on **input fields** generated by the library. I thought it was related to this issue, but I see it is closed. The code in fact seems to take it into account.
Has anyone been able to have the placeholder float on an input field or is it a bug of Material directly? 

Thanks,
Sallaccio

#### Problem:
Trying to replicate `floatLabel="auto"` on a `mat-form-field` containing an `input`. Placeholder does not "float" when first character is entered: it just disappears.

**Comment by Jascen** [comment]
@sallaccio,

Please review issue [#109](https://github.com/hamzahamidi/Angular6-json-schema-form/issues/109) for a potential workaround.

**Comment by sallaccio** [comment]
Thank you for your reply. 
I will check as soon as possible.
