### ISSUE TITLE
Where to refer for basic features' API. How to validate fields with pattern.

### ISSUE THREAD

**Issue by sai7** [hamzahamidi/ajsf#23]
**Describe the bug**
No guide on how to make changes. (For example, if I need to make "arrays" not draggable, it is not available.)
which template:

* [ √] MaterialDesignFrameworkModule — Material Design
* [ ] Bootstrap3FrameworkModule — Bootstrap 3
* [ ] Bootstrap4FrameworkModule — Bootstrap 4
* [ ] NoFrameworkModule — plain HTML
* [ ] Other (please specify below)
  
Thanks for this exciting repo. It does all the expected work. 

To get some insights, I can refer to the examples in the playground. But I am limited to not using the complete API.

For any feature, I need to refer most of the previous issues on angular2-json-schema-form's repo.

To disable/enable the form, I need to use **'defautWidgetOptions': { 'readonly': true }**, as opposed the API, "**formReadonly: true**", which is available in the **defaultFormOptions** method of **/lib/son-schema-form.service.ts** file

**Detailed Description**
Please provide me, how to:

1. Add **basic Validation** on form fields. How to use **patterns** and **validate** the form field based on the pattern.
2. How to **toggle** the complete form to make it **read-only** and vice-versa.

**Context**

In the forms, basic validation is must for formatting fields like email, telephone, currency etc.,

This will reduce the hard work to include custom functions.

**Possible Implementation**
Please add the API usage documentation or point to one.

Thanks :)

**Comment by danielbarela** [comment]
This is still an issue.
