### ISSUE TITLE
Support for custom locale validation messages

### ISSUE THREAD

**Issue by neil-coutinho** [hamzahamidi/ajsf#24]
**Describe the bug**
which template:

* [ ] MaterialDesignFrameworkModule — Material Design
* [ ] Bootstrap3FrameworkModule — Bootstrap 3
* [x] Bootstrap4FrameworkModule — Bootstrap 4
* [ ] NoFrameworkModule — plain HTML
* [ ] Other (please specify below)
  
Currently, we have support English and French validation messages. In addition, we can provide validation messages by using one of the 3 available methods i.e.

* String: A plain text message, which is always the same.
* String template: A text message that includes Angular template-style {{variables}}, which will be be replaced with values from the returned error object.
* Function: A JavaScript function which accepts the error object as input, and returns a string error message.

Is there an option where in my custom widget component I can subscribe to a language change event and trigger and update to update the layoutNode's validationMessages? 

Trying to support Spanish and a few other custom languages in my forms

```
 this.languageSwitch.currentLang
        .subscribe(data => {

         this.options.validationMessages.required = 'CUSTOM_LANGUAGE_STRING

      });

```

**To Reproduce**

1. ...

**Expected behavior**
In my custom widget I am subscribed to a language Subject Observable. When I received an updated value the validation messages for the form should update.

**Screenshots**

**Desktop (please complete the following information):**

**Log output covering before error and any error statements**

```logs
Insert log hereCopy
```

**Additional context**

**Detailed Description**

**Context**

**Possible Implementation**

**Comment by hamzahamidi** [comment]
Currently we support only two languages English & French [See Here .](https://github.com/hamzahamidi/Angular6-json-schema-form/tree/9498b6a74932d2e6ab4e30b6e7c2de3967ff37f7/projects/angular6-json-schema-form/src/lib/locale) If you want to add support to another language, I ask you to create a Pull Request and add the localization file like the following for [french language ](https://github.com/hamzahamidi/Angular6-json-schema-form/blob/9498b6a74932d2e6ab4e30b6e7c2de3967ff37f7/projects/angular6-json-schema-form/src/lib/locale/fr-validation-messages.ts).

**Comment by meherfattouch** [comment]
wanteeed.com/join/b13dea9bfb054cec8c741a4e51df63ef
