### ISSUE TITLE
Npm versions vs Github versions number

### ISSUE THREAD

**Issue by jonathanantoine** [hamzahamidi/ajsf#267]
**Describe the bug**
Can you explain me the versionning of npm packages ? There is some 0.1.x versions on npm and the release of githubs are 9.0.0, 10.0.0, etc. 
I would like to be able to identifiy what's new in each release.

Thanks

**Comment by jonathanantoine** [comment]
@hamzahamidi  please :)

**Comment by hamzahamidi** [comment]
You can see that information in the releases changelog https://github.com/hamzahamidi/ajsf/releases
