### ISSUE TITLE
JsonSchemaFormService is a singleton instance. This prevents use the component more than once in an application

### ISSUE THREAD

**Issue by tproenca** [hamzahamidi/ajsf#280]
JsonSchemaFormService is a singleton instance. This prevents use the component more than once in an application since they shared the same state.

which template:

* [X ] MaterialDesignFrameworkModule — Material Design
* [X] Bootstrap3FrameworkModule — Bootstrap 3
* [X] Bootstrap4FrameworkModule — Bootstrap 4
* [X] NoFrameworkModule — plain HTML
* [X] Other (please specify below)
  
JsonSchemaFormService is a singleton instance. This prevents use the component more than once in an application since they shared the same state.

**To Reproduce**
Create more than one <json-schema-form></json-schema-form> component in a page with different schemas. Once you start typing in one component, it will mirror the state of the last component of the form.

**Expected behavior**
The components should work independently.  

**Screenshots**

**Desktop (please complete the following information):**

**Log output covering before error and any error statements**

```logs
Insert log hereCopy
```

**Additional context**

**Detailed Description**

**Context**

**Possible Implementation**

**Comment by tproenca** [comment]
The fix is easy. I'm working on it and testing and as soon I have it done I'll push a pull request.

**Comment by hamzahamidi** [comment]
Fixed starting from https://www.npmjs.com/package/@ajsf/core/v/0.5.1-beta.3, see changelog https://github.com/hamzahamidi/ajsf/releases/tag/13.1.2
