### ISSUE TITLE
How To update dropdown select

### ISSUE THREAD

**Issue by olawale12** [hamzahamidi/ajsf#34]
this is not an issue this is a question have been on it for some time now
how can I update value of dropdown select after the form is been rendered

**Comment by bhamscott** [comment]
Do you mean updating select options (titleMap) with dynamic data or updating select based on value from another select?

I have a similar need in that I need to be able to specify a dynamic titlemap either via URL or user-defined callback.

**Comment by anasofiapaixao** [comment]
I am currently using a workaround that [allows me to do that in a generic enough way](https://stackoverflow.com/a/55169728), combined with [a workaround for `onChange` callbacks to work](https://github.com/hamzahamidi/Angular6-json-schema-form/issues/37#issuecomment-472967887).
