### ISSUE TITLE
radio buttons in array - changes radio state in different array entries 

### ISSUE THREAD

**Issue by dror-rash** [hamzahamidi/ajsf#42]
**Describe the bug**
which template:

* [√] MaterialDesignFrameworkModule — Material Design
* [√ ] Bootstrap3FrameworkModule — Bootstrap 3
* [ ] Bootstrap4FrameworkModule — Bootstrap 4
* [√ ] NoFrameworkModule — plain HTML
* [ ] Other (please specify below)
  
radio buttons in an array change radio button state in other array entries 
**To Reproduce**
for the schema, bellow add array items and hit radio buttons. changes affect different array entries 

{
  "schema": {
    "title": "Comment",
    "type": "object",
    "properties": {
      "comments": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "something": {
              "title": "Radio",
              "type": "string"
            }
          }
        }
      }
    }
  },
  "form": [
    { "key": "comments",
      "add": "New",
      "style": { "add": "btn-success" },
      "items": [
        {
            "key": "comments[].something",
            "type": "radios-inline",
            "titleMap": [
                {"name": "A", "value": "a"},
                {"name": "B", "value": "b"},
                {"name": "C", "value": "c"},
            ]
        }
      ]
    },
    { "title": "OK",
      "type": "submit",
      "style": "btn-info"
    }
  ]
}

**Desktop (please complete the following information):**

- OS: [e.g. iOS] - IOS 12
- Browser [e.g. chrome, safari] - Chrome & Opera

**Log output covering before error and any error statements**

```logs
Insert log hereCopy
```

**Additional context**

**Detailed Description**

**Context**

**Possible Implementation**

**Comment by hamzahamidi** [comment]
Thank you @dror-rash for discovering this bug. I'm checking this right now.

**Comment by ChristosAsvestopoulos** [comment]
I am experiencing exactly the same issue.
