### ISSUE TITLE
Slow with big json data

### ISSUE THREAD

**Issue by opiria-pdata** [hamzahamidi/ajsf#43]
**Describe the bug**
which template:

* [x] MaterialDesignFrameworkModule — Material Design
* [x] Bootstrap3FrameworkModule — Bootstrap 3
* [x] Bootstrap4FrameworkModule — Bootstrap 4
* [x] NoFrameworkModule — plain HTML
* [ ] Other (please specify below)
  

**To Reproduce**

1. Open the  [demo page](https://hamidihamza.com/Angular6-json-schema-form/)
2. Load the data from this file [data.zip](https://github.com/hamzahamidi/Angular6-json-schema-form/files/2614152/data.zip)
3. Try to edit fields

**Expected behavior**
The changing of input values need to be smooth

**Desktop (please complete the following information):**

- Browser Chrome Version 70.0.3538.110 (Official Build) (64-bit)

**Comment by hamzahamidi** [comment]
Thank you for your note @opiria-pdata . When working with big Json schemas the complexity rises up  it takes time to load in the dom. I'll check this out. In the mean time you're welcome if you have any suggestions.

**Comment by lasimone** [comment]
This is still relevant. When using a big JSON structure, trying to load the DOM in the browser's developer tools is almost impossible because it is so slow.

**Comment by Den-dp** [comment]
I'm wondering, is it possible to integrate Virtual Scrolling feature from https://material.angular.io/cdk/scrolling/overview ?
