### ISSUE TITLE
Giving error for draft-04

### ISSUE THREAD

**Issue by sachin5590** [hamzahamidi/ajsf#46]
**Describe the bug**
When I try to use your library to generate form, based on draft-04 version. I get this error:

no schema with key or ref "http://json-schema.org/draft-06/schema#"

Here is the json schema that I am using: 

{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Contact",
  "type": "object",
  "properties": {
    "work": {
      "$ref": "#/definitions/phone"
    },
    "home": {
      "$ref": "#/definitions/phone"
    }
  },
  "definitions": {
    "phone": {
      "type": "object",
      "properties": {
        "number": {
          "type": "string"
        },
        "extension": {
          "type": "string"
        }
      }
    }
  }
}

**Desktop (please complete the following information):**

- OS: OS X El Captain
- Browser: All
- Version: 10.11.6

**Comment by RS-Roshi** [comment]
I think you should remove
"$schema": "http://json-schema.org/draft-04/schema#",
From your schema then check it. 
I hope it will work

**Comment by sachin5590** [comment]
But how will the module know which version I am using.

**Comment by RS-Roshi** [comment]
By default library will convert the schema to schema draft 6 so don't worry about that

**Comment by sachin5590** [comment]
Ok and Thanks for your solution. It is working now.

**Comment by RS-Roshi** [comment]
That's great and close the issue now...
