### ISSUE TITLE
bug(layout): array of array is missing the 2nd sub element

### ISSUE THREAD

**Issue by Mathou54** [hamzahamidi/ajsf#47]
**Describe the bug**
which template:

* [x] MaterialDesignFrameworkModule — Material Design
* [x] Bootstrap3FrameworkModule — Bootstrap 3
* [x] Bootstrap4FrameworkModule — Bootstrap 4
* [x] NoFrameworkModule — plain HTML
* [ ] Other (please specify below)
  

**To Reproduce**

1. got to https://hamidihamza.com/Angular6-json-schema-form/
2. past 
```json
{
  "schema": {
      "type": "object",
      "properties": {
          "value1": {"type": "string"},
          "array1": {
              "type": "array",
              "items": {
                  "type": "array",
                  "items": {
                      "type": "string"
                  }
              }
          }
      }
    
  },
  "layout": [
      {"key": "value1"},
      {"key": "array1",
          "type": "array",
          "items": [{
              "key": "array1[]",
              "type": "array",
              "items": [{
                 "key": "array1[][]",
                  "type": "string"
              }]
          }]
      }
  ],
  "data": {
      "value1": "value1",
      "array1":[["array11", "array12"], ["array21"]]
  }
}
```
 as type.

**Expected behavior**
`array1[0]` should display the 2nd elements (array12).

**Desktop (please complete the following information):**

**Log output covering before error and any error statements**

```logs
Insert log hereCopy
```

**Additional context**

**Comment by RS-Roshi** [comment]
Something is wrong with your schema..
You're saying array1 is array type its inside object is array type and in subarray there is a string object.. 
Array
_____subArray
______________string(inside the sub array)
And you're using layout to adjust the schema.. Layout is used to adjust the  form widgets like input fields drop down.. Youre schema is invalid please get help from test examples first before writing ur schema

**Comment by RS-Roshi** [comment]
> 
> 
> But why the data I pass is marked valid? (An object containing an array of array of string.)
> This means the schema is the right one (or at least the schema and data are ok, maybe the layout is wrong).

as by my thoughts of this library ,, layout is used to adjust the positioning and somethings like that kindly i refer you to check its given examples.

**Comment by scottux** [comment]
Removing the layout definition altogether displays the form as I think you expect it to be.

**Comment by mkormendy** [comment]
Another issue unresolved and closed by a bot .... @hamzahamidi @alekart @richard-cox @earlyster @mcrodrig @knaveen01 @kenisteward @guileh @bogdanbaghiu @Tian-Hun @SamuelMarks @JohnDoee @FMerco @BobCashStory Can one of you please reopen as this issue?
