### ISSUE TITLE
List reorder / click and drag mouse up does nothing, however desired effect happens after following click

### ISSUE THREAD

**Issue by james-powis** [hamzahamidi/ajsf#48]
**Describe the bug**
which template:  - All-of-em

* [x] MaterialDesignFrameworkModule — Material Design
* [x] Bootstrap3FrameworkModule — Bootstrap 3
* [x] Bootstrap4FrameworkModule — Bootstrap 4
* [x] NoFrameworkModule — plain HTML
* [ ] Other (please specify below)
  
I apologize for the vagueness of this report, I am at wits end and unable to provide much detail as to the cause, or remedy of the problem.

On an orderable array (aka draggable), the drag function appears to not work unless you follow up the drag action with a click action on one of the elements in the list. This is not present in the demo and I cannot replicate the behavior in the demo with what is being see locally. 

**Expected behavior**
A mouse up event after drag should alter order, however in my experience, the mouse up does nothing but a following mouse down and up (aka click) then produces the desired result.

**Desktop (please complete the following information):**

OSX 10.13.6 (17G3025)
Chrome
70.0.3538.110 (Official Build) (64-bit)

Note this is also present in Safari 12.0.1 (13606.2.104.1.2)

**Log output covering before error and any error statements**
No errors observed

**Comment by james-powis** [comment]
Here is a project which does not render well but demonstrates the issue: https://github.com/james-powis/angular6-json-schema-form-issue

**Comment by james-powis** [comment]
I have upgraded the application to angular8 and @ajsf/material 0.1.3 and this issue persists. If there is anything I can provide to help troubleshoot this please let me know... Also debug is entirely silent.

**Comment by hamzahamidi** [comment]
@james-powis  can you push your upgrade to the remote repository https://github.com/james-powis/angular6-json-schema-form-issue? I'll check this asap

**Comment by james-powis** [comment]
@hamzahamidi I have updated the repo to use Angular9 and the latest and greatest of all other dependencies including ajsf.

There are 3 cards (phone numbers: 1111111, 222222, 3333333). If you try and drag 3333333 into the second array position you will see that that drag event is not realized, now click on 1111111 and magically 3333333 will go from the 3rd array position to the second and 222222 will be in the third.

I have yet to figure out why this happens, so I am thankful for your response as my users are frequently joking about this behavior in my app...

**Comment by james-powis** [comment]
@hamzahamidi One other thing I have noticed since upgrading the example repo to NG9 (as well as our internal app) is that lists are no longer ordered in rows, they have defaulted to being column ordered. I will create a separate issue for this if I find one does not already exist.
