### ISSUE TITLE
Addable sections not removable in NoFramework

### ISSUE THREAD

**Issue by vytcus** [hamzahamidi/ajsf#59]
Addable sections cannot be removed when no framework is chosen - no "X", remove button, or similar is visible. This can be reproduced in the demo by chosing None (Plain HTML):
[https://hamidihamza.com/Angular6-json-schema-form/](url)

**Comment by szarkowicz** [comment]
Does anyone have a way to delete / remove an item from the array if the Plain HTML framework is selected?
