### ISSUE TITLE
How to specify options for widgets

### ISSUE THREAD

**Issue by knorze** [hamzahamidi/ajsf#62]
I found out, that you can provide options to properties directly in the schema. 

Example:
The following snippet adds the option "floatLabel" to the property "first_name". If you select "material-design" as framework, then the label of the corresponding input field is always shown above the input field

```
{
  "schema": {
    "type": "object",
    "properties": {
      "first_name": {
          "type": "string",
          "floatLabel": "always"
      }
    }
  }
}

```
My problem is now, that I don't have control over the schema. I receive it from a web service.
I just want to specify the options for a widget type once, which shall then be applied to all widgets of this type. Can such options be specified somewhere, e.g. in the global options object?

**Comment by samudiogo** [comment]
@knorze Did you found a solution? Could you share it?

**Comment by knorze** [comment]
No sorry. This topic got out of focus for me.
