### ISSUE TITLE
Issue with Integer Field on Firefox

### ISSUE THREAD

**Issue by wmsimpso1** [hamzahamidi/ajsf#77]
**Describe the bug**
which template:

* [x] MaterialDesignFrameworkModule — Material Design
* [ ] Bootstrap3FrameworkModule — Bootstrap 3
* [ ] Bootstrap4FrameworkModule — Bootstrap 4
* [ ] NoFrameworkModule — plain HTML
* [ ] Other (please specify below)
  
The integer field on chrome restricts all non numeric characters aside from e and ".".  On firefox 65, there's no restirction on non numeric characters
**To Reproduce**

1. Open Firefox
2. https://hamidihamza.com/Angular6-json-schema-form/?set=rjsf&example=rjsf-numbers&framework=material-design&language=en
3. On the field that auto populates with 42, type any non numeric character, and it will be entered into the input box

**Expected behavior**
Either the same behavior as chrome, where most characters are restricted, or total restriction of non-numeric characters
**Screenshots**
![image](https://user-images.githubusercontent.com/47432119/52439899-acb88b00-2aea-11e9-97c3-5a6b4b662e70.png)

**Desktop (please complete the following information):**

- OS: [e.g. iOS] macOs 10.14.2
- Browser [e.g. chrome, safari] Firefox
- Version [e.g. 22] 65

**Log output covering before error and any error statements**

```logs
Insert log hereCopy
```

**Additional context**

**Detailed Description**

**Context**

**Possible Implementation**

**Comment by gennarocc** [comment]
I've looked into this and this appears to be a bug with the material input field.

(Try in Firefox)
https://stackblitz.com/edit/angular-qoqgsx?file=app/input-overview-example.html

**Comment by wmsimpso1** [comment]
![image](https://user-images.githubusercontent.com/47432119/53585321-9e8ee500-3b53-11e9-94c5-474d958f26e3.png)
From firefox

**Comment by gennarocc** [comment]
https://github.com/angular/material2/issues/4941
