### ISSUE TITLE
Bootstrap grid broken

### ISSUE THREAD

**Issue by matthelliwell2** [hamzahamidi/ajsf#81]
**Describe the bug**
which template:

* [ ] MaterialDesignFrameworkModule — Material Design
* [ ] Bootstrap3FrameworkModule — Bootstrap 3
* [* ] Bootstrap4FrameworkModule — Bootstrap 4
* [ ] NoFrameworkModule — plain HTML
* [ ] Other (please specify below)
  

**To Reproduce**

Go to the grid example at https://hamidihamza.com/Angular6-json-schema-form/?set=asf&example=asf-bootstrap-grid&framework=bootstrap-4&language=en

Name and email fields appear beneath each other

**Expected behavior**
I would expect name and email fields to appear side by side.

**Screenshots**

**Desktop (please complete the following information):**

- OS:windows 10
- Browser chrome
- Version: Version 71.0.3578.98 (Official Build) (64-bit)

**Additional context**
Same problem happens in IE. It looks like the htmlClass in a section is ignored.

**Comment by vishnu-dev** [comment]
Any updates on this?

**Comment by SushiGuy** [comment]
Figured out the problem today. Bootstrap 3 layouts work with embedded divs, of which there are many that the schema engine generates. Sample below in v3 respects the widths of both "col-3" widths. In v4 the second "col-3" one shrinks.
`<div class="row">
   <div class="col-3">Hello</div>
   <div>
      <root-widget>
         <div class="col-3">Hello World</div>
      </root-widget>
   </div>
</div>`

Bootstrap 4 does not do well with nested divs, only working if there is no nesting like sample below. You can experiment at [W3schools.com Tryit Editor](https://www.w3schools.com/bootstrap4/tryit.asp?filename=trybs_grid_ex_structure&stacked=h).

`<div class="row">
   <div class="col-3">Hello</div>
   <div class="col-3">Hello World</div>
</div>`

Bootstrap 4 is a significant code rewrite, and is based on the new [CSS Flexbox](https://www.w3schools.com/css/css3_flexbox.asp) framework. Hopefully by embracing the flex styling, which this engine supports, the 12 grid system can still be achieved. Will post back here if a workaround is achieved.

**Comment by SushiGuy** [comment]
Bootstrap Grid system can be achieved by

1. Using "Flexbox layout"
2. Using "Bootstrap 4" Framework

Try the following in the [demo site](https://hamidihamza.com/Angular6-json-schema-form/). First row shows automatic flex layout. Second row shows grid layout. The grid layout requires more typing than Bootstrap's `class="col-1"` but it works. Here is the full list of column widths, the values taken directly from the Bootstrap library.

"flex": "0 1 8.333333%" - col-1
"flex": "0 1 16.66666%" - col-2
"flex": "0 1 25%" - col-3
"flex": "0 1 33.333333%" - col-4
"flex": "0 1 41.666667%" - etc
"flex": "0 1 50%"
"flex": "0 1 58.333333%"
"flex": "0 1 66.666667%"
"flex": "0 1 75%"
"flex": "0 1 83.333333%"
"flex": "0 1 91.666667%"
"flex": "0 1 100%"

```
{
  "schema": {
    "type": "object",
    "properties": {
      "first_name": { "type": "string" },
      "middle_initial": { "type": "string" },
      "last_name": { "type": "string" },
      "city": { "type": "string" },
      "state": { "type": "string" },
      "zip_code": { "type": "string" }
    }
  },
  "layout": [
    { "type": "flex", "flex-flow": "row wrap", "items": [ "first_name", "middle_initial", "last_name" ] },
    { "type": "div",
      "display": "flex",
      "flex-direction": "row",
      "items": [
        { "key": "city", "flex": "0 1 25%",
          "notitle": true, "placeholder": "City"
        },
        { "key": "state", "flex": "0 1 8.333333%",
          "notitle": true, "placeholder": "State"
        },
        { "key": "zip_code", "flex": "0 1 16.66666%",
          "notitle": true, "placeholder": "Zip Code"
        }
      ]
    }
  ]
}
```

P.S. After pasting JSON into demo, the textarea needs to lose focus or have a keypress for the Generated Form to update.

**Comment by SushiGuy** [comment]
I have a fix to add grid support, per the style below. Example shows a "col-3" Bootstrap equivalent, and under the hood mirrors BS4 with a flex percentage style. Also valid is "flex-grid": "3 9" if you want to work off a 9-column grid instead of the default 12-column. Any tips on how to commit a branch?

```
 {
   "key": "firstName",
   "flex-grid": "3"
 }
```

_C:\git push --set-upstream origin bugfix/bootstrap-grid_
_Permission to hamzahamidi/Angular6-json-schema-form.git denied to SushiGuy_

**Comment by hamzahamidi** [comment]
Thank you @SushiGuy If you want to make a pull request you need to fork the project then git clone from your forked project.
