### ISSUE TITLE
Adding capability for external $ref URLs

### ISSUE THREAD

**Issue by kenisteward** [hamzahamidi/ajsf#92]
I would like some information on how I can possibly add the capability of resolving external $ref URLs.  The library resolves local definitions references wonderfully.

I think resolveSchemaReferences() in the json-schema.functions.ts might be where I want to start but I'm not sure.  I basically want to hook into what's there and say "if the $ref is a url and not in the current map of references go get it and cache it as we do other references"

**Comment by neil-coutinho** [comment]
@hamzahamidi

**Comment by johnnemo** [comment]
Hello! Any update on this? I try to use a schema from a git submodule and thus I am not able to edit its contents.. Ideally I would like to use $ref and allOf for the schema properties and then append the "layout" if needed. The submodule is cloned inside the project.. Is there any way to merge the schemas and use the library?
