### ISSUE TITLE
Enable dynamic select - URL or callback for titleMap

### ISSUE THREAD

**Issue by bhamscott** [hamzahamidi/ajsf#97]
**Detailed Description**
* [ ] MaterialDesignFrameworkModule — Material Design
 
1. Would like to implement something similar to strapSelect to specify a dynamically populated select, radio or checkboxes control.

**Context**
User can specify a callback or URL to grab dynamic titlemaps. Returned data (name/value pairs) should automatically be mapped to name/value titlemaps regardless of the name/value descriptors used in the input. For example, an incoming data object of {"id": "1", "city": "Birmingham"} would be mapped to { "name": "1", "value": "Birmingham" }

**Possible Implementation**
Suggest to implement something similar to strapSelect but with Angular Material support.

**Comment by samudiogo** [comment]
Hi @bhamscott ,
I made an example using [@anasofiapaixao](https://github.com/anasofiapaixao) with some adaptations:
[https://stackblitz.com/edit/angular-json-schema-form-dynamic-select-data-form-demo](https://stackblitz.com/edit/angular-json-schema-form-dynamic-select-data-form-demo)

#37
